name: brens
on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install pandas
        run: pip install pandas

      - name: Say hi from Python
        run: echo "hi from python"

  Turkey:
    needs: validate
    runs-on: ubuntu-latest
    steps:
        - name: say hi thanksgiving
          run: pip install matplotlib
        - name: what
          run: echo "The Secret is cooking a chicken is ${{ secrets.BRENDANS }}"

      
